FROM ruby:3.4.7

ARG UID=1000
ARG GID=1000

RUN groupadd -g ${GID} app && useradd -m -u ${UID} -g ${GID} -s /bin/bash app

USER root

RUN set -eux; \
    apt-get update -qq && apt-get install -y --no-install-recommends \
      build-essential pkg-config libpq-dev \
      postgresql-client \
      libvips libvips-dev \
      curl ca-certificates gnupg wget iproute2 \
      nodejs npm \
      libgirepository1.0-dev gobject-introspection gir1.2-glib-2.0 \
      dos2unix \
      git \
    ; \
    rm -rf /var/lib/apt/lists/*

WORKDIR /rails

RUN gem install bundler -v '4.0.4'

RUN rm -f Gemfile.lock

COPY --chown=${UID}:${GID} Gemfile Gemfile.lock ./
ENV BUNDLE_PATH=/usr/local/bundle

RUN bundle install --jobs 4 --retry 3

COPY --chown=${UID}:${GID} entrypoint.dev.sh ./entrypoint.dev.sh

RUN dos2unix ./entrypoint.dev.sh

RUN chmod +x ./entrypoint.dev.sh

COPY --chown=${UID}:${GID} . .

COPY --chown=${UID}:${GID} package.json ./package.json
COPY --chown=${UID}:${GID} package-lock.json ./package-lock.json

# if some dependency have older, legacy, packages, just install
RUN npm config set legacy-peer-deps true

RUN npm install
RUN bundle exec vite install

RUN chown -R ${UID}:${GID} /rails /usr/local/bundle

USER app

ENV RAILS_ENV=development \
    NODE_ENV=development \
    VITE_HOST=0.0.0.0 \
    VITE_RUBY_HOST=0.0.0.0 \
    VITE_PORT=3040 \
    CHOKIDAR_USEPOLLING=true \
    BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3 \
    BUNDLE_FROZEN=1

EXPOSE 3000 3040

HEALTHCHECK --interval=3s --timeout=2s --retries=30 --start-period=10s \
  CMD curl -fsS http://127.0.0.1:3000/up >/dev/null || exit 1


ENTRYPOINT ["/rails/entrypoint.dev.sh"]
